# Generated by Django 6.0.2 on 2026-02-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_author_alter_comment_author_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('text', 'Standard text post'), ('image', 'Post with image attachment'), ('video', 'Post with video attachment'), ('article', 'Long-form article post'), ('poll', 'Interactive poll post')], default='text', max_length=20),
        ),
    ]
